"""Generate backend/tools/postgrest.conf from backend/.env.

    python scripts/write_postgrest_config.py

Why this is a script and not a documented command. The config embeds a database
password, so it cannot be committed, which means every installation regenerates
it by hand. It started as a one-liner in the README; it now carries six settings
and two of them are safety-relevant, which is exactly the shape of thing that
drifts between what the README says and what a machine is actually running.

The output goes to backend/tools/, which is gitignored in full.

WARNING: `postgrest --dump-config` prints db-uri INCLUDING THE PASSWORD in
cleartext. Do not paste its output into an issue, a log or a commit.
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from etl.config import (  # noqa: E402
    API_ANON_ROLE,
    BACKEND_DIR,
    ConfigError,
    api_authenticator_db,
    postgrest_settings,
)

TEMPLATE = """\
# PostgREST configuration for lang-nav.
#
# GENERATED by scripts/write_postgrest_config.py from backend/.env.
# Do not hand-edit: change .env and re-run. This file is gitignored along with
# the rest of backend/tools/, because db-uri contains a credential.
#
# Start with:  tools/postgrest tools/postgrest.conf

db-uri = "postgres://{user}:{password}@{host}:{port}/{dbname}"

# Only this schema is exposed. Nothing outside it is reachable over HTTP.
db-schemas = "public"

# The role every unauthenticated request runs as. PostgREST connects as the
# authenticator and immediately SET ROLEs to this one, which is the only reason
# the authenticator is granted membership in it.
db-anon-role = "{anon_role}"

server-port = {server_port}

# Which origins may call this from a browser. An EMPTY value means "any origin",
# which is what this served before and is wrong anywhere but localhost.
server-cors-allowed-origins = "{cors_origins}"

# A BACKSTOP AGAINST A RUNAWAY QUERY, NOT A PAGE SIZE.
#
# Read this before lowering it. PostgREST caps the rows it returns at this
# number, and a capped response is INDISTINGUISHABLE FROM A COMPLETE ONE to the
# frontend: Content-Range comes back as `0-99999/*`, where the total after the
# slash is literally an asterisk unless the client asks for a count. No loader
# asks today, so a cap that can actually be reached would silently truncate the
# data and every downstream number would be quietly wrong.
#
# The value is therefore set ABOVE the largest table rather than to a
# comfortable page size. The number to beat is `locale`, at 54,731 rows.
#
# To tighten this, the loaders must first detect truncation. The mechanism
# exists and is cheap: `Prefer: count=planned` makes Content-Range report the
# real total (`0-27298/27299`) using the planner's estimate rather than a COUNT,
# and measured no slower than omitting it.
db-max-rows = {max_rows}

# No JWT secret is set, so there is no way to authenticate as anything other
# than the anonymous role. Every request is read-only by construction.
"""


def main() -> int:
    try:
        api = api_authenticator_db()
        settings = postgrest_settings()
    except ConfigError as exc:
        print(f"configuration error: {exc}", file=sys.stderr)
        return 2

    out_dir = BACKEND_DIR / "tools"
    if not out_dir.is_dir():
        print(
            f"{out_dir} does not exist. Download the PostgREST binary into it "
            f"first; see backend/README.md.",
            file=sys.stderr,
        )
        return 1

    body = TEMPLATE.format(
        # Percent-encoded: a password containing @ / : or # would otherwise
        # break the URI into pieces at the wrong place.
        user=api.user,
        password=quote(api.password, safe=""),
        host=api.host,
        port=api.port,
        dbname=api.dbname,
        anon_role=API_ANON_ROLE,
        server_port=settings.server_port,
        cors_origins=settings.cors_origins,
        max_rows=settings.max_rows,
    )

    target = out_dir / "postgrest.conf"
    target.write_text(body, encoding="utf-8")

    # Report without the credential.
    print(f"wrote {target}")
    print(f"  connection  : {api.redacted()}")
    print(f"  anon role   : {API_ANON_ROLE}")
    print(f"  port        : {settings.server_port}")
    print(f"  cors origins: {settings.cors_origins}")
    print(f"  max rows    : {settings.max_rows}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
