import { LocaleSource } from '@entities/locale/LocaleTypes';

export function getLocaleSourceLabel(localeSource: LocaleSource) {
  switch (localeSource) {
    case LocaleSource.StableDatabase:
      return 'Regular Database'; // >1% of world pop of language, or >1% of country or >1M speakers or official recognition
    case LocaleSource.IANA:
      return 'IANA Language Tag Registry';
    case LocaleSource.Census:
      return 'Census Record';
    case LocaleSource.CreateRegionalLocales:
      return 'Generated by adding up locales inside countries';
  }
}
