import { LocaleSource } from '@entities/locale/LocaleTypes';

import enforceExhaustiveSwitch from '@shared/lib/enforceExhaustiveness';

export function getLocaleSourceLabel(localeSource: LocaleSource) {
  switch (localeSource) {
    case LocaleSource.StableDatabase:
      return 'Regular Database'; // >1% of world pop of language, or >1% of country or >1M speakers or official recognition
    case LocaleSource.IANA:
      return 'IANA Language Tag Registry';
    case LocaleSource.Census:
      return 'Census Record';
    case LocaleSource.CreateRegionalLocales:
      return 'Generated by adding up locales inside countries';
    case LocaleSource.CreateFamilyLocales:
      return 'Generated by combining languages into their language family.';
    default:
      enforceExhaustiveSwitch(localeSource);
  }
}
