/**
 * Types for CLDR locale support. These types mirror the structure of the
 * objects generated by the build script in scripts/ingest/build-cldr-locales.ts.
 */

export interface CLDRLocaleSupport {
  /** Full BCP-47 locale, e.g. "en_US" */
  locale: string;
  /** Language code, e.g. "en" */
  language: string;
  /** Region code, e.g. "US" (optional) */
  region?: string;
  /** Script code, e.g. "Latn" (optional) */
  script?: string;

  /** Tier of locale support: core, modern or full */
  tier: 'core' | 'modern' | 'full';

  /**
   * True if this locale is listed in defaultContent.json. Indicates that the
   * locale is the default content locale for its language.
   */
  localeIsDefaultForLanguage?: boolean;

  /** Whether a corresponding XML exists in CLDR repo */
  presentInCLDRDatabase?: boolean;

  /** Coverage target (modern/moderate/basic/core) */
  targetLevel?: string;
  /** Coverage computed level */
  computedLevel?: string;

  /** Aggregate % confirmed */
  confirmedPct?: number;

  /** Breakdown percentages (optional) */
  pctModern?: number;
  pctModerate?: number;
  pctBasic?: number;
  pctCore?: number;

  /** True if the locale is included in ICU datasets (per charts) */
  icuIncluded?: boolean;

  /** Charts’ default region column (if present) */
  defaultRegion?: string;

  /** Missing feature tokens from charts */
  notes?: string[];

  /** Counts at target level */
  missingCounts?: {
    found: number;
    unconfirmed: number;
    missing: number;
  };
}

export interface CLDRLocaleIndex {
  release: string;
  generatedAt: string;
  locales: CLDRLocaleSupport[];
}
